#version 450

layout( local_size_x = 32) in;

layout( set = 0, binding = 0 , r32f) uniform imageBuffer A;
layout( set = 0, binding = 1 , r32f) uniform imageBuffer B;
layout( set = 0, binding = 2 , r32f) uniform imageBuffer C;

void main() {
	uint Lxid = gl_GlobalInvocationID.x;
    float a = imageLoad(A, int(Lxid) ).x;
    float b = imageLoad(B, int(Lxid) ).x;
    float c = a + b;

    imageStore(C,int(Lxid),vec4(c,0,0,0)); 
}